SmatWatering/BookListMVC/Models/DevicePin.cs
using SmartWatering.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookListMVC.Models
{
    public class DevicePin : IEntityDate
    {
        [Key]
        public int PinId { get; set; }
        [Display(Name = "PIN Description")]
        public string Description { get; set; }
        public string PIN { get; set; }
        [Display(Name = "Chip ID")]
        public int chipId { get; set; }
        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Updated Date")]
        public DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}

SmatWatering/BookListMVC/Controllers/DevicePinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SmartWatering.Models;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace SmartWatering.Controllers
{
    public class DevicePinsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;
        public DevicePinsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }

        [HttpGet]
        public async  Task<IActionResult> GetInfo(int _chipId, int type)//type=0 In/ 1=out
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return new JsonResult(_context.DevicePin
                            .Where(x => x.chipId == _chipId && x.PinType == (Util.PinType)type)
                            .Select(x => new { value = x.PIN + ": " + x.Description, x.PIN }));
            }
            var x = _context.DevicePin
                         .Where(x => x.chipId == _chipId && x.CreatedBy == LoginUserId && x.PinType == (Util.PinType)type)
                         .Select(x => new { value = x.PIN + ": " + x.Description, x.PIN });
            return new JsonResult(x);
        }

        // GET: DevicePins
        public async Task<IActionResult> Index(int?id )
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id == null)
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(await _context.DevicePin.ToListAsync());
                }
                return View(await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync());
            }
            else
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(await _context.DevicePin.Where(m => m.chipId == id).ToListAsync());
                }
                return View(await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId && c.chipId==id).ToListAsync());
            }
        }

        // GET: DevicePins/Create
        public IActionResult Create()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var value = from c in _context.Device
                        where c.CreatedBy == LoginUserId
                        select c.ChipId;
            ViewBag.Chips=  value;

            return View();
        }

        // POST: DevicePins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PinType, PinId,PIN,chipId,Description")] DevicePin devicePin)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            devicePin.CreatedBy = LoginUserId;
            devicePin.UpdatedBy = LoginUserId;
            if (ModelState.IsValid)
            {
                _context.Add(devicePin);
              _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(devicePin);
        }

        // GET: DevicePins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var devicePin = await _context.DevicePin.FindAsync(id);

            if (devicePin == null)
            {
                return View("NotFound");
            }
            if (devicePin.CreatedBy != LoginUserId && !(await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View("AccessDenied");
            }

            var value = from c in _context.Device
                        where c.CreatedBy == LoginUserId
                        select c.ChipId;
            ViewBag.Chips = value;
            return View(devicePin);
        }

        // POST: DevicePins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PinId, CreatedBy, PinType, PIN,chipId,Description,CreatedDate,UpdatedDate")] DevicePin devicePin)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id != devicePin.PinId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    devicePin.UpdatedBy = LoginUserId;
                    _context.Update(devicePin);
                  _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DevicePinExists(devicePin.PinId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(devicePin);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var devicePin = new DevicePin();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                devicePin = await _context.DevicePin.FindAsync(id);
            }
            else
            {
                devicePin = await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId && c.PinId == id)
                    .FirstOrDefaultAsync();
            }
            if (devicePin == null)
                return Json(new { status = false, message = "Error while Deleting" });
            _context.DevicePin.Remove(devicePin);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });

        }

        private bool DevicePinExists(int id)
        {
            return _context.DevicePin.Any(e => e.PinId == id);
        }
    }
}

SmatWatering/BookListMVC/Controllers/VariablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using SmartWatering.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using SmartWatering.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SmartWatering.Controllers
{
    public class VariablesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;

        public VariablesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }

        // GET: Variables
        public async Task<IActionResult> Index(int? id)
        {
            var variable = _context.Variable;
            var devicePin = _context.DevicePin;
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variables = (from v in variable
                             join d in devicePin on v.PinId equals d.PinId
                             select new VariableView
                             {
                                 VariableId = v.VariableId,
                                 VariableName = v.VariableName,
                                 PIN = d.PIN,
                                 ChipId = d.chipId,
                                 CreatedDate = v.CreatedDate,
                                 UpdatedDate = v.UpdatedDate,
                                 CreatedBy = v.CreatedBy,
                                 PinId = v.PinId
                             }).ToList();
            if( id == null)
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(variables);
                }
                return View(variables.Where(c => c.CreatedBy == LoginUserId).ToList());
            }
            else
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(variables.Where(c => c.PinId==id).ToList());
                }
                return View(variables.Where(c => c.CreatedBy == LoginUserId && c.PinId == id).ToList());
            }
           
        }

        // GET: Variables/Create
        public async Task <IActionResult> Create()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var x = await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            ViewBag.Values = (List<DevicePin>) await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            return View();
        }

        // POST: Variables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create(VariableView model)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Variable variable = new Variable();
            if (ModelState.IsValid)
            {
                variable.VariableName = model.VariableName;
                variable.PinId = _context.DevicePin.Where( c => c.chipId==model.ChipId && c.PIN==model.PIN).FirstOrDefault().PinId;
                variable.CreatedBy = LoginUserId;
                variable.UpdatedBy = LoginUserId;
                _context.Add(variable);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(variable);
        }

        // GET: Variables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variable = (from v in _context.Variable
                           join d in _context.DevicePin on v.PinId equals d.PinId
                           where v.VariableId == id && v.CreatedBy == LoginUserId
                           select new VariableView
                           {
                               VariableId = v.VariableId,
                               VariableName = v.VariableName,
                               PIN = d.PIN,
                               ChipId = d.chipId,
                               PinId = v.PinId,
                               CreatedDate = v.CreatedDate,
                               UpdatedDate = v.UpdatedDate,
                               CreatedBy = v.CreatedBy
                           }).Single();



            if (variable == null)
            {
                return View("NotFound");
            }
          
            ViewBag.Values = (List<DevicePin>)await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            return View(variable);
        }

        // POST: Variables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("VariableId,VariableName,PinId,CreatedDate,UpdatedDate, CreatedBy")] Variable variable)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id != variable.VariableId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    variable.UpdatedBy = LoginUserId;
                    _context.Update(variable);
                     _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VariableExists(variable.VariableId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(variable);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variable = new Variable();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                variable = await _context.Variable.FindAsync(id);
            }
            else
            {
                variable = await _context.Variable.Where(c => c.CreatedBy == LoginUserId && c.VariableId == id)
                    .FirstOrDefaultAsync();
            }
            if (variable == null)
                return Json(new { status = false, message = "Error while Deleting" });
            _context.Variable.Remove(variable);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });

        }
        private bool VariableExists(int id)
        {
            return _context.Variable.Any(e => e.VariableId == id);
        }
    }
}

SmatWatering/BookListMVC/Views/DevicePins/Create.cshtml
@model BookListMVC.Models.DevicePin
@using SmartWatering.Util;
@{
    ViewData["Title"] = "Create";
    var Chips = ViewBag.Chips;
}

<div class="row">
    <div class="col-6">
        <h2 class="h3 mb-2 text-gray-800 text-info">Create Device pin </h2>
    </div>

</div>
<hr />

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Create" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="PinType" class="control-label col-4"></label>
                                <select asp-for="PinType" class="form-control col-5">
                                    @{foreach (var e in (PinType[])Enum.GetValues(typeof(PinType)))
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="PinType" class="text-danger"></span>
                            </div>

                            <div class="form-group row justify-content-center">
                                <label asp-for="PIN" class="control-label col-4"></label>
                                <input asp-for="PIN" class="form-control col-5">
                                <span asp-validation-for="PIN" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="chipId" class="control-label col-4"></label>
                                <select asp-for="chipId" class="form-control col-5">
                                    @{foreach (var e in Chips)
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="chipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Description" class="control-label col-4"></label>
                                <input asp-for="Description" class="form-control col-5">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Create" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-controller="DevicePins" asp-action="Index">Back to List</a>
</div>

SmatWatering/BookListMVC/Views/DevicePins/Edit.cshtml
@model BookListMVC.Models.DevicePin
@using SmartWatering.Util;
@{
    ViewData["Title"] = "Edit";
    var Chips = ViewBag.Chips;

}
<h1>Edit</h1>

<h4>DevicePin</h4>
<hr />
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Edit" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="PinId" />
                            <input type="hidden" asp-for="CreatedBy" />

                            <div class="form-group row justify-content-center">
                                <label asp-for="PinType" class="control-label col-4"></label>
                                <select asp-for="PinType" class="form-control col-5">
                                    @{foreach (var e in (PinType[])Enum.GetValues(typeof(PinType)))
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="PinType" class="text-danger"></span>
                            </div>

                            <div class="form-group row justify-content-center">
                                <label asp-for="PIN" class="control-label col-4"></label>
                                <input asp-for="PIN" id="PIN" class="form-control col-5">
                                <span asp-validation-for="PIN" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Description" class="control-label col-4"></label>
                                <input asp-for="Description" id="Description" class="form-control col-5">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="chipId" class="control-label col-4"></label>
                                <select asp-for="chipId" class="form-control col-5">
                                    @{foreach (var e in Chips)
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="chipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Submit" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

SmatWatering/BookListMVC/Views/DevicePins/Index.cshtml
@model IEnumerable<BookListMVC.Models.DevicePin>

@{ ViewData["Title"] = "Index"; }


<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        @*<h1 class="h3 mb-2 text-gray-800 text-info">Device Pins</h1>

        <p class="mb-4">
            <a asp-action="Create">Create New</a>
        </p>*@
        <div class="row">
            <div class="col-6">
                <h2 class="h3 mb-2 text-gray-800 text-info">Device Pins </h2>
            </div>
            <div class="col-6 text-right">
                <a class="btn btn-primary text-white"  asp-action="Create"><i class="fas fa-plus"></i> &nbsp; Create New  </a>
            </div>
        </div>
        @*<h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p>*@

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.PIN)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.chipId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PinType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UpdatedDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a asp-controller="Variables" asp-action="Index" asp-route-id="@item.PinId"> @Html.DisplayFor(modelItem => item.PIN)</a>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.chipId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PinType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.PinId"><i style="margin-right : 5px" class="text-info fas fa-pen fa-lg"></i></a> |
                                        <a onclick='Delete("/DevicePins/Delete/@item.PinId" ,false)'><i style="margin-left : 5px" class="text-danger fas fa-trash fa-lg"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@section Scripts{
    <script src="~/js/toatr.js"></script>
    <script src="~/js/demo/datatables-demo.js"></script>
}