SmatWatering/BookListMVC/Models/Variable.cs
using SmartWatering.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookListMVC.Models
{
    public class Variable : IEntityDate
    {
        [Key]
        public int VariableId { get; set; }
        [Display(Name = "Variable Name")]
        public string VariableName { get; set; }
        public int PinId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}

SmatWatering/BookListMVC/Controllers/VariableValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using SmartWatering.Models.ViewModels;
using Nancy.Json;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SmartWatering.Models;
using System.Security.Claims;

namespace SmartWatering.Controllers
{
    public class VariableValuesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;

        public VariableValuesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }

        //api
        public async Task<IActionResult> ApiIndex()
        {
            //var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var count = _context.VariableValue.Count();
            var variableValues = from v in _context.VariableValue
                                 join e in _context.Variable on v.VariableId equals e.VariableId
                                 join d in _context.DevicePin on e.PinId equals d.PinId
                                 orderby v.VariableValueId descending
                                 select new VariableValueView
                                 {
                                     VariableValueId = v.VariableValueId,
                                     VariableName = e.VariableName,
                                     Value = v.Value,
                                     PIN = d.PIN,
                                     ChipId = d.chipId,
                                     CreatedBy = e.CreatedBy,
                                     CreatedDate = v.CreatedDate.ToString("dd/MM/yyyy HH:mm:ss")
                                 };
            //if (!(await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            //{
            //    variableValues = variableValues.Where(c => c.CreatedBy == LoginUserId);
            //}
            return Json(new { quantity = count, data = variableValues });
        }

        // GET: VariableValues
        [HttpGet, ActionName("Index")]
        public async Task<IActionResult> Index()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var variableValues = await (from v in _context.VariableValue
                                        join e in _context.Variable on v.VariableId equals e.VariableId
                                        join d in _context.DevicePin on e.PinId equals d.PinId
                                        select new VariableValueView
                                        {
                                            VariableValueId = v.VariableValueId,
                                            Value = v.Value,
                                            VariableName = e.VariableName,
                                            PIN = d.PIN,
                                            ChipId = d.chipId,
                                            CreatedBy = e.CreatedBy,
                                            VariableId = v.VariableId,
                                            CreatedDate = v.CreatedDate.ToString("dd-mm-yyyy HH:mm:ss")
                                        }).ToListAsync();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View(variableValues);
            }
            return View(variableValues.Where(c => c.CreatedBy == LoginUserId).ToList());
        }

        // GET: VariableValues
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var variableValues = await (from v in _context.VariableValue
                                        join e in _context.Variable on v.VariableId equals e.VariableId
                                        join d in _context.DevicePin on e.PinId equals d.PinId
                                        select new VariableValueView
                                        {
                                            VariableValueId = v.VariableValueId,
                                            Value = v.Value,
                                            VariableName = e.VariableName,
                                            PIN = d.PIN,
                                            ChipId = d.chipId,
                                            CreatedBy = e.CreatedBy,
                                            VariableId = v.VariableId,
                                            CreatedDate = v.CreatedDate.ToString("dd-mm-yyyy HH:mm:ss")
                                        }).ToListAsync();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View(variableValues.Where(c => c.VariableId == id).ToList());
            }
            return View(variableValues.Where(c => c.CreatedBy == LoginUserId && c.VariableId == id).ToList());
        }
        // GET: VariableValues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VariableValues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("VariableValueId,Value,VariableId,CreatedDate")] VariableValue variableValue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(variableValue);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(variableValue);
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var bookFromDb = await _context.VariableValue.FirstOrDefaultAsync(u => u.VariableValueId == id);
            if (bookFromDb == null)
            {
                return Json(new { status = false, message = "Error while Deleting" });
            }
            _context.VariableValue.Remove(bookFromDb);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });
        }
        //[HttpDelete]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //    var variableValue = new VariableValue();
        //    if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
        //    {
        //        variableValue = await _context.VariableValue.FindAsync(id);
        //    }
        //    else
        //    {
        //        //variableValue = (from v in _context.VariableValue
        //        //                 join d in _context.Variable on v.VariableId equals d.VariableId
        //        //                 where d.CreatedBy == LoginUserId && v.VariableValueId == id
        //        //                 select new VariableValue
        //        //                 {
        //        //                     VariableValueId = v.VariableId,
        //        //                     Value = v.Value,
        //        //                     VariableId = v.VariableId,
        //        //                     CreatedDate = v.CreatedDate,
        //        //                     UpdatedDate = v.UpdatedDate
        //        //                 }).FirstOrDefault();
        //        variableValue = await _context.VariableValue.FirstOrDefaultAsync(u => u.VariableValueId == id);
        //    }
        //    if (variableValue == null)
        //        return Json(new { status = false, message = "Error while Deleting" });
        //    _context.VariableValue.Remove(variableValue);
        //    await _context.SaveChangesAsync();
        //    return Json(new { status = true, message = "Delete successful" });

        //}
        private bool VariableValueExists(int id)
        {
            return _context.VariableValue.Any(e => e.VariableValueId == id);
        }
    }
}

SmatWatering/BookListMVC/Controllers/VariablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using SmartWatering.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using SmartWatering.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SmartWatering.Controllers
{
    public class VariablesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;

        public VariablesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }

        // GET: Variables
        public async Task<IActionResult> Index(int? id)
        {
            var variable = _context.Variable;
            var devicePin = _context.DevicePin;
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variables = (from v in variable
                             join d in devicePin on v.PinId equals d.PinId
                             select new VariableView
                             {
                                 VariableId = v.VariableId,
                                 VariableName = v.VariableName,
                                 PIN = d.PIN,
                                 ChipId = d.chipId,
                                 CreatedDate = v.CreatedDate,
                                 UpdatedDate = v.UpdatedDate,
                                 CreatedBy = v.CreatedBy,
                                 PinId = v.PinId
                             }).ToList();
            if( id == null)
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(variables);
                }
                return View(variables.Where(c => c.CreatedBy == LoginUserId).ToList());
            }
            else
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(variables.Where(c => c.PinId==id).ToList());
                }
                return View(variables.Where(c => c.CreatedBy == LoginUserId && c.PinId == id).ToList());
            }
           
        }

        // GET: Variables/Create
        public async Task <IActionResult> Create()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var x = await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            ViewBag.Values = (List<DevicePin>) await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            return View();
        }

        // POST: Variables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create(VariableView model)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Variable variable = new Variable();
            if (ModelState.IsValid)
            {
                variable.VariableName = model.VariableName;
                variable.PinId = _context.DevicePin.Where( c => c.chipId==model.ChipId && c.PIN==model.PIN).FirstOrDefault().PinId;
                variable.CreatedBy = LoginUserId;
                variable.UpdatedBy = LoginUserId;
                _context.Add(variable);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(variable);
        }

        // GET: Variables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variable = (from v in _context.Variable
                           join d in _context.DevicePin on v.PinId equals d.PinId
                           where v.VariableId == id && v.CreatedBy == LoginUserId
                           select new VariableView
                           {
                               VariableId = v.VariableId,
                               VariableName = v.VariableName,
                               PIN = d.PIN,
                               ChipId = d.chipId,
                               PinId = v.PinId,
                               CreatedDate = v.CreatedDate,
                               UpdatedDate = v.UpdatedDate,
                               CreatedBy = v.CreatedBy
                           }).Single();



            if (variable == null)
            {
                return View("NotFound");
            }
          
            ViewBag.Values = (List<DevicePin>)await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync();
            return View(variable);
        }

        // POST: Variables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("VariableId,VariableName,PinId,CreatedDate,UpdatedDate, CreatedBy")] Variable variable)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id != variable.VariableId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    variable.UpdatedBy = LoginUserId;
                    _context.Update(variable);
                     _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VariableExists(variable.VariableId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(variable);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var variable = new Variable();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                variable = await _context.Variable.FindAsync(id);
            }
            else
            {
                variable = await _context.Variable.Where(c => c.CreatedBy == LoginUserId && c.VariableId == id)
                    .FirstOrDefaultAsync();
            }
            if (variable == null)
                return Json(new { status = false, message = "Error while Deleting" });
            _context.Variable.Remove(variable);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });

        }
        private bool VariableExists(int id)
        {
            return _context.Variable.Any(e => e.VariableId == id);
        }
    }
}

SmatWatering/BookListMVC/Views/Variables/Create.cshtml
@model VariableView

@{
    ViewData["Title"] = "Create";
    var Values = (List<DevicePin>)ViewBag.Values;
    var ChipIds = Values.Select(c => c.chipId).Distinct().ToList();
}

    <div class="row">
        <div class="col-6">
            <h2 class="h3 mb-2 text-gray-800 text-info">Create variable </h2>
        </div>
    </div>
<hr />

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Create" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group row justify-content-center">
                                <label asp-for="VariableName" class="control-label col-4"></label>
                                <input asp-for="VariableName" class="form-control col-5">
                                <span asp-validation-for="VariableName" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="ChipId" class="control-label col-4"></label>
                                <select asp-for="ChipId" class="form-control col-5" onchange="Load()" onclick="Load()">
                                    @{foreach (var e in ChipIds)
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="ChipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="PIN" class="control-label col-4"></label>
                                <select asp-for="PIN" class="form-control col-5"></select>
                                <span asp-validation-for="PIN" class="text-danger"></span>
                            </div>
                            
                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Create" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-controller="Variables" asp-action="Index">Back to List</a>
</div>
<script src="~/js/Load.js"></script>
   

SmatWatering/BookListMVC/Views/Variables/Edit.cshtml
@model VariableView

@{
    ViewData["Title"] = "Edit";
    var Values = (List<DevicePin>)ViewBag.Values;
    var ChipIds = Values.Select(c => c.chipId).Distinct().ToList();

}

<h1>Edit</h1>

<h4>Variable</h4>
<hr />

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Edit" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="VariableId" />
                            <input type="hidden" asp-for="CreatedBy" />
                            <input type="hidden" asp-for="PinId" />

                            <div class="form-group row justify-content-center">
                                <label asp-for="VariableName" class="control-label col-4"></label>
                                <input asp-for="VariableName" id="VariableName" class="form-control col-5">
                                <span asp-validation-for="VariableName" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="ChipId" class="control-label col-4"></label>
                                <select asp-for="ChipId" class="form-control col-5" onchange="Load()" onclick="Load()">
                                    @{foreach (var e in ChipIds)
                                        {
                                            <option value="@e">@e</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="ChipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="PIN" class="control-label col-4"></label>
                                <select asp-for="PIN" class="form-control col-5"></select>
                                <span asp-validation-for="PIN" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Save" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/js/Load.js"></script>

SmatWatering/BookListMVC/Views/Variables/Index.cshtml
@model IEnumerable<SmartWatering.Models.ViewModels.VariableView>

@{ ViewData["Title"] = "Index"; }

<!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        
        <div class="row">
            <div class="col-6">
                <h2 class="h3 mb-2 text-gray-800 text-info">Variables </h2>
            </div>
            <div class="col-6 text-right">
                <a class="btn btn-primary text-white"  asp-action="Create"><i class="fas fa-plus"></i> &nbsp; Create New Variables </a>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.VariableName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VariableId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PIN)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ChipId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UpdatedDate)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <a asp-controller="VariableValues" asp-action="Details" asp-route-id="@item.VariableId"> @Html.DisplayFor(modelItem => item.VariableName)</a>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.VariableId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PIN)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ChipId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.VariableId"><i style="margin-right : 5px" class="text-info fas fa-pen fa-lg"></i></a> |
                                        <a onclick='Delete("/Variables/Delete/@item.VariableId" ,false)'><i style="margin-left : 5px" class="text-danger fas fa-trash fa-lg"></i></a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@section Scripts{
    <script src="~/js/toatr.js"></script>
    <script src="~/js/demo/datatables-demo.js"></script>
}