SmatWatering/BookListMVC/Models/Device.cs
using SmartWatering.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookListMVC.Models
{
    public class Device :IEntityDate
    {
        [Key]
        public int DeviceId { get; set; }
        public string Name { get; set; }
        [Display(Name = "Chip ID")]
        public int ChipId { get; set; }
        public string Description { get; set; }
        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Updated Date")]
        public DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string  ReadAPIKey { get; set; }
        public string  WriteAPIKey { get; set; }

    }
}

SmatWatering/BookListMVC/Models/ViewModels/DeviceView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmartWatering.Models.ViewModels
{
    public class DeviceView
    {
        [Display(Name = "Chip ID")]
        public int ChipId { get; set; }
        public string Description { get; set; }
    }
}

SmatWatering/BookListMVC/ViewModels/DeviceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartWatering.ViewModels
{
    public class DeviceViewModel
    {
        public int ChipId { get; set; }
        public string Description { get; set; }
    }
}

SmatWatering/BookListMVC/Controllers/DevicePinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SmartWatering.Models;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;

namespace SmartWatering.Controllers
{
    public class DevicePinsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;
        public DevicePinsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }

        [HttpGet]
        public async  Task<IActionResult> GetInfo(int _chipId, int type)//type=0 In/ 1=out
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return new JsonResult(_context.DevicePin
                            .Where(x => x.chipId == _chipId && x.PinType == (Util.PinType)type)
                            .Select(x => new { value = x.PIN + ": " + x.Description, x.PIN }));
            }
            var x = _context.DevicePin
                         .Where(x => x.chipId == _chipId && x.CreatedBy == LoginUserId && x.PinType == (Util.PinType)type)
                         .Select(x => new { value = x.PIN + ": " + x.Description, x.PIN });
            return new JsonResult(x);
        }

        // GET: DevicePins
        public async Task<IActionResult> Index(int?id )
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id == null)
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(await _context.DevicePin.ToListAsync());
                }
                return View(await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId).ToListAsync());
            }
            else
            {
                if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
                {
                    return View(await _context.DevicePin.Where(m => m.chipId == id).ToListAsync());
                }
                return View(await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId && c.chipId==id).ToListAsync());
            }
        }

        // GET: DevicePins/Create
        public IActionResult Create()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var value = from c in _context.Device
                        where c.CreatedBy == LoginUserId
                        select c.ChipId;
            ViewBag.Chips=  value;

            return View();
        }

        // POST: DevicePins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PinType, PinId,PIN,chipId,Description")] DevicePin devicePin)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            devicePin.CreatedBy = LoginUserId;
            devicePin.UpdatedBy = LoginUserId;
            if (ModelState.IsValid)
            {
                _context.Add(devicePin);
              _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(devicePin);
        }

        // GET: DevicePins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var devicePin = await _context.DevicePin.FindAsync(id);

            if (devicePin == null)
            {
                return View("NotFound");
            }
            if (devicePin.CreatedBy != LoginUserId && !(await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View("AccessDenied");
            }

            var value = from c in _context.Device
                        where c.CreatedBy == LoginUserId
                        select c.ChipId;
            ViewBag.Chips = value;
            return View(devicePin);
        }

        // POST: DevicePins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PinId, CreatedBy, PinType, PIN,chipId,Description,CreatedDate,UpdatedDate")] DevicePin devicePin)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id != devicePin.PinId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    devicePin.UpdatedBy = LoginUserId;
                    _context.Update(devicePin);
                  _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DevicePinExists(devicePin.PinId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(devicePin);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var devicePin = new DevicePin();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                devicePin = await _context.DevicePin.FindAsync(id);
            }
            else
            {
                devicePin = await _context.DevicePin.Where(c => c.CreatedBy == LoginUserId && c.PinId == id)
                    .FirstOrDefaultAsync();
            }
            if (devicePin == null)
                return Json(new { status = false, message = "Error while Deleting" });
            _context.DevicePin.Remove(devicePin);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });

        }

        private bool DevicePinExists(int id)
        {
            return _context.DevicePin.Any(e => e.PinId == id);
        }
    }
}

SmatWatering/BookListMVC/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookListMVC.Models;
using SmartWatering.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using SmartWatering.Models;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using SmartWatering.Util;

namespace SmartWatering.Controllers
{
    [Authorize]
    public class DevicesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> userManager;
        private IAuthorizationService authorizationService;


        public DevicesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            IAuthorizationService authorizationService)
        {
            _context = context;
            this.userManager = userManager;
            this.authorizationService = authorizationService;
        }
        public async Task<IActionResult> GetInfo()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var val = _context.Device.Select(x => new { x.Name, x.ChipId });

            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return new JsonResult(_context.Device.Select(x => new { x.Name, x.ChipId }));
            }
            return new JsonResult( _context.Device.Where(c => c.CreatedBy == LoginUserId)
                                                    .Select(x => new { x.Name, x.ChipId }));
        }
        // GET: Devices
       
        public IActionResult ApiIndex()
        {
            var count = _context.Device.Count();
            var devices = from v in _context.Device
                          orderby v.CreatedDate descending
                          select new DeviceView
                          {
                              ChipId = v.ChipId,
                              Description = v.Description
                          };
            return Json(new { quantity = count, data = devices });
        }

        public async Task<IActionResult> Index()
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View(await _context.Device.ToListAsync());
            }
            return View(await _context.Device.Where(c => c.CreatedBy == LoginUserId).ToListAsync());
        }
       

        // GET: Devices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create([Bind("DeviceId, Name, ChipId,Description")] Device device)
        {

            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (LoginUserId == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {LoginUserId} cannot be found";
                return View("NotFound");
            }
            device.CreatedBy = LoginUserId;
            device.UpdatedBy = LoginUserId;
            device.WriteAPIKey = GenerateToken.Generate();
            device.ReadAPIKey = GenerateToken.Generate();
            if (ModelState.IsValid)
            {
                _context.Add(device);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var device = await _context.Device.FindAsync(id);
            
            if (device == null)
            {
                return View("NotFound");
            }
            if(device.CreatedBy!=LoginUserId && !(await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View("AccessDenied");
            }
            return View(device);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var device = await _context.Device.FindAsync(id);

            if (device == null)
            {
                return View("NotFound");
            }
            if (device.CreatedBy != LoginUserId && !(await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                return View("AccessDenied");
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("DeviceId, Name, ChipId,Description, CreatedBy, WriteAPIKey, ReadAPIKey")] Device device)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (id != device.DeviceId)
            {
                return View("NotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    device.UpdatedBy = LoginUserId;
                    _context.Update(device);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.DeviceId))
                    {
                        return View("NotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var LoginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var device = new Device();
            if ((await authorizationService.AuthorizeAsync(User, "AdminPolicy")).Succeeded)
            {
                device = await _context.Device.FindAsync(id);
            }
            else
            {
                device = await _context.Device.Where(c => c.CreatedBy == LoginUserId && c.DeviceId == id)
                    .FirstOrDefaultAsync();
            }
            if (device == null)
                return Json(new { status = false, message = "Error while Deleting" });
            _context.Device.Remove(device);
            await _context.SaveChangesAsync();
            return Json(new { status = true, message = "Delete successful" });
            
        }
        private bool DeviceExists(int id)
        {
            return _context.Device.Any(e => e.DeviceId == id);
        }

    }
}

SmatWatering/BookListMVC/Views/Devices/Create.cshtml
@model BookListMVC.Models.Device

@{ ViewData["Title"] = "Create"; }

<h1>Create</h1>

<h4>Device</h4>
<hr />
@*<div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ChipId" class="control-label"></label>
                    <input asp-for="ChipId" class="form-control" />
                    <span asp-validation-for="ChipId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>*@
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Create" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group row justify-content-center">
                                <label asp-for="Name" class="control-label col-4"></label>
                                <input asp-for="Name" id="ChipId" class="form-control col-5">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div> 
                            <div class="form-group row justify-content-center">
                                <label asp-for="ChipId" class="control-label col-4"></label>
                                <input asp-for="ChipId" id="ChipId" class="form-control col-5">
                                <span asp-validation-for="ChipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Description" class="control-label col-4"></label>
                                <input asp-for="Description" id="Description" class="form-control col-5">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Submit" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

<script src="~/js/control.js"></script>
<script src="~/js/toatr.js"></script>

SmatWatering/BookListMVC/Views/Devices/Details.cshtml
@model BookListMVC.Models.Device

@{
    ViewData["Title"] = "Edit";
}

<h2 class="h3 mb-2 text-gray-800 text-info">Details of device </h2>
<hr />


<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Edit" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="DeviceId" class="control-label col-4"></label>
                                <input asp-for="DeviceId" class="form-control col-5" readonly>
                                <span asp-validation-for="DeviceId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Name" class="control-label col-4"></label>
                                <input asp-for="Name" class="form-control col-5" readonly>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="ChipId" class="control-label col-4"></label>
                                <input asp-for="ChipId" class="form-control col-5" readonly>
                                <span asp-validation-for="ChipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Description" class="control-label col-4"></label>
                                <input asp-for="Description" class="form-control col-5" readonly>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="ReadAPIKey" class="control-label col-4"></label>
                                <input asp-for="ReadAPIKey" class="form-control col-5" readonly>
                                <span asp-validation-for="ReadAPIKey" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="WriteAPIKey" class="control-label col-4"></label>
                                <input asp-for="WriteAPIKey" class="form-control col-5" readonly>
                                <span asp-validation-for="WriteAPIKey" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="CreatedDate" class="control-label col-4"></label>
                                <input asp-for="CreatedDate" class="form-control col-5" readonly>
                                <span asp-validation-for="CreatedDate" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="UpdatedDate" class="control-label col-4"></label>
                                <input asp-for="UpdatedDate" class="form-control col-5" readonly>
                                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SmatWatering/BookListMVC/Views/Devices/Edit.cshtml
@model BookListMVC.Models.Device

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Device</h4>
<hr />

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4  ">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"></h6>
                </div>
                <div class="card-body">
                    <div class="row ">
                        <form asp-action="Edit" class="col-12 justify-content-center">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="DeviceId" />
                            <input type="hidden" asp-for="CreatedBy" />
                            <input type="hidden" asp-for="ReadAPIKey" />
                            <input type="hidden" asp-for="WriteAPIKey" />
                            <div class="form-group row justify-content-center">
                                <label asp-for="Name" class="control-label col-4"></label>
                                <input asp-for="Name" id="ChipId" class="form-control col-5">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div> 
                            <div class="form-group row justify-content-center">
                                <label asp-for="ChipId" class="control-label col-4"></label>
                                <input asp-for="ChipId" id="ChipId" class="form-control col-5">
                                <span asp-validation-for="ChipId" class="text-danger"></span>
                            </div>
                            <div class="form-group row justify-content-center">
                                <label asp-for="Description" class="control-label col-4"></label>
                                <input asp-for="Description" id="Description" class="form-control col-5">
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            <div class="form-group row justify-content-center">
                                <input type="submit" value="Save" class="btn btn-primary btn-icon-split btn-lg  col-3 " />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SmatWatering/BookListMVC/Views/Devices/Index.cshtml
@model IEnumerable<BookListMVC.Models.Device>

@{ ViewData["Title"] = "Index"; }

<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="row">
        <div class="col-6">
            <h2 class="h3 mb-2 text-gray-800 text-info">List of devices </h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary text-white" asp-controller="Devices" asp-action="Create"><i class="fas fa-plus"></i> &nbsp; Create New Device </a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>  
                            <th>
                                @Html.DisplayNameFor(model => model.ChipId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ReadAPIKey)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.WriteAPIKey)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a asp-controller="DevicePins" asp-action="Index" asp-route-id="@item.ChipId"> @Html.DisplayFor(modelItem => item.Name)</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ChipId)
                                </td> 
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReadAPIKey)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.WriteAPIKey)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedDate)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.DeviceId"><i style="margin-right : 5px" class="text-info fas fa-pen fa-lg"></i> </a> |
                                    <a asp-action="Details" asp-route-id="@item.DeviceId"><i style="margin-right : 5px" class="text-warning fas fa-info-circle fa-lg"></i> </a> |
                                    <a onclick='Delete("/Devices/Delete/@item.DeviceId" ,false)'> <i style="margin-left : 5px" class="text-danger fas fa-trash fa-lg"></i></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

@section Scripts{
    <script src="~/js/toatr.js"></script>
    <script src="~/js/demo/datatables-demo.js"></script>
}